version: "3.8"
services:
  devbox:
    image: millim.no/devbox:2.2.0-a6
    env_file: "stack.env"
    build: "./"
    volumes:
      # - "/your/path/to/files:/srv/portfolio"
      # - "/your/path/to/config/files:/srv/apache"
      # - "/etc/certbot/live/example.com:/srv/certs"
      # - "/home/user/.ssh:/ssh"  # Where you placed github.key
      - "srv:/srv"
      - "ssh:/ssh"
    pull_policy: build
    restart: always
    ports:
      - 80:80
      - 443:443
volumes:
  srv:
  ssh:
