version: "3.8"
services:
  devbox:
    image: millim.no/devbox:2.0.0-a1
    env_file: "stack.env"
    build: "./"
    volumes:
      - "srv:/srv"
      - "ssh:/ssh"
    pull_policy: build
    ports:
      - 80:80
      - 443:443
volumes:
  srv:
  ssh:
