version: "3.8"
services:
  devbox:
    image: container.millim.no/millim/webhost:2.2.0-a7
    env_file: "stack.env"
    build: "webhost"
    volumes:
      - "./srv/apache:/srv/apache"
      - "./srv/webprojects:/srv/portfolio"
      - "./srv/certs:/srv/certs"
      - "./srv/ssh:/ssh"
    pull_policy: build
    restart: always
    ports:
      - "80:80"
      - "443:443"
  dns:
    image: container.millim.no/millim/dnsmasq:1.2.1
    env_file: "stack.env"
    build:
      context: dns
      target: production
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./dnsmasq:/srv"
